# Generated by Django 5.2.12 on 2026-04-23 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(verbose_name='first name')),
                ('last_name', models.CharField(blank=True, verbose_name='last name')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('priority', models.IntegerField(default=0, verbose_name='priority')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='query')),
                ('count', models.IntegerField(default=0, verbose_name='count')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('home_page', models.URLField(blank=True, verbose_name='home page')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(verbose_name='term')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='title')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='publication date')),
                ('authors', models.ManyToManyField(blank=True, to='context.author', verbose_name='authors')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.collection', verbose_name='collection')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('lemmas', models.TextField(verbose_name='lemmas')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.document', verbose_name='document')),
            ],
        ),
        migrations.CreateModel(
            name='SourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='link')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.source', verbose_name='source')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.term', verbose_name='term')),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(verbose_name='source name')),
                ('definition', models.TextField(verbose_name='definition')),
                ('source_url', models.URLField(blank=True, verbose_name='URL')),
                ('accessed', models.DateTimeField(auto_now=True, null=True, verbose_name='accessed')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.source', verbose_name='source')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.term', verbose_name='term')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='index')),
                ('form', models.CharField(verbose_name='form')),
                ('lemma', models.CharField(verbose_name='lemma')),
                ('upos', models.CharField(max_length=10, verbose_name='UPOS')),
                ('xpos', models.CharField(max_length=10, verbose_name='XPOS')),
                ('features', models.CharField(blank=True, verbose_name='features')),
                ('head', models.IntegerField(null=True, verbose_name='head')),
                ('deprel', models.CharField(blank=True, max_length=10, verbose_name='deprel')),
                ('misc', models.CharField(blank=True, verbose_name='misc')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='context.sentence', verbose_name='sentence')),
            ],
        ),
    ]
